name: "Ruby Hash Selector Pattern"
slug: "ruby-hash-selector-pattern"
cover: "hash-selector-icon.png"
description: "We show you an alternative to if / else and case / switch."
video: "http://www.youtube.com/watch?v=Pyg-31Nhd8I"
tags: ["Ruby"]
free: true