name: "Rails Flash Partials"
slug: "rails-flash-partials"
description: "How to setup flash messages in your application"
video: "http://www.youtube.com/watch?v=rSlDEvtk6lA"
tags: ["Rails"]
playlists: ["A Shot of Rails"]
cover: "cover.png"