title: "Ruby Hash Selector Pattern"
slug: "ruby-hash-selector-pattern"
tags: ["Ruby"]
playlists: ["A Shot of Ruby"]
details:
  blurb: "We show you an alternative to if / else and case / switch."
  cover: "assets/hash-selector-icon.png"
